In [675]:
import torch
torch.__version__

'2.0.0.dev20230111'

In [676]:
x = torch.tensor([10], dtype=float,requires_grad=True)
y = torch.tensor([20], dtype=float,requires_grad=True)

z = 2 * x ** 3 + 3 * y ** 2
z.backward()

print(x.grad,y.grad)

tensor([600.], dtype=torch.float64) tensor([120.], dtype=torch.float64)


In [677]:
import torch
import random
class Neuron:
    def __init__(self, numInputs = 0):
#        random.seed(1)
        self.numInputs = numInputs
        self.weights =[torch.tensor([random.uniform(-1,1)], dtype=float,requires_grad=True) for _ in range(numInputs)]
        self.bias = torch.tensor([random.uniform(-1,1)],dtype= float, requires_grad= True)

    def __call__(self, x):
        sum = torch.tensor([0],dtype=float)
        for wi,xi in zip(self.weights, x):
            sum+=wi*xi
        return (sum+self.bias).tanh()
    
    def parameters(self):
        return self.weights + [self.bias]

n = Neuron(numInputs=3)
#output = n([torch.tensor([1],dtype= float, requires_grad= True),torch.tensor([2],dtype= float, requires_grad= True),torch.tensor([3],dtype= float, requires_grad= True)])
output = n([1.0,2.0,3.0])
output.backward()

for w in n.weights:
    print(w.grad)
print(n.bias)
len(n.parameters())

tensor([0.0557], dtype=torch.float64)
tensor([0.1114], dtype=torch.float64)
tensor([0.1670], dtype=torch.float64)
tensor([-0.5461], dtype=torch.float64, requires_grad=True)


4

In [678]:
class Layer:
    def __init__(self,numInputs=0,numOutputs=0):
        self.neurons = [Neuron(numInputs) for _ in range(numOutputs)]
    
    def __call__(self,x):
        return [n(x) for n in self.neurons]
    
    def parameters(self):
        p = []
        for neuron in self.neurons:
            p.extend(neuron.parameters())
        return p


In [679]:
x = Layer(3,4)
x([1,2,3])
len(x.parameters())

16

In [680]:
class MLP:
    def __init__(self,numInputs=0, numOutputs=[]):
        sz = [numInputs] + numOutputs
        self.layers = []
        for i in range(len(numOutputs)):
            self.layers.append(Layer(sz[i],sz[i+1]))
    def __call__(self,x):
        for layer in self.layers:
            x = layer(x)
        return x[0] if len(x)==1 else p   
    def parameters(self):
        p = []
        for layer in self.layers:
            p.extend(layer.parameters())
        return p
mlp = MLP(3,[4,4,4,1])
out = mlp([1,2,3])
len(mlp.parameters())

61

In [681]:
xs = [[2.0,3.0,-1.0],
      [3.0,-1.0,0.5],
      [0.5,1.0,1.0],
    [1.0,1.0,-1.0]];

ys = [1.0, -1.0, -1.0, 1.0]




In [682]:
yPred = []
for epoch in range(20):
    yPred = [mlp(x) for x in xs]
    loss = sum([(yP-y)**2 for yP,y in zip(yPred,ys)])

    #zero grad
    for p in mlp.parameters():
        p.grad = None

    #backward
    loss.backward()

    #update params
    for p in mlp.parameters():
        p.data += -0.1 * p.grad

    print(loss.data)

tensor([6.5965], dtype=torch.float64)
tensor([4.4885], dtype=torch.float64)
tensor([3.7026], dtype=torch.float64)
tensor([3.9012], dtype=torch.float64)
tensor([5.1843], dtype=torch.float64)
tensor([3.5682], dtype=torch.float64)
tensor([4.5573], dtype=torch.float64)
tensor([1.4964], dtype=torch.float64)
tensor([0.3814], dtype=torch.float64)
tensor([0.1681], dtype=torch.float64)
tensor([0.1343], dtype=torch.float64)
tensor([0.1117], dtype=torch.float64)
tensor([0.0954], dtype=torch.float64)
tensor([0.0832], dtype=torch.float64)
tensor([0.0737], dtype=torch.float64)
tensor([0.0661], dtype=torch.float64)
tensor([0.0599], dtype=torch.float64)
tensor([0.0547], dtype=torch.float64)
tensor([0.0503], dtype=torch.float64)
tensor([0.0466], dtype=torch.float64)


In [683]:
yPred

[tensor([0.8764], dtype=torch.float64, grad_fn=<TanhBackward0>),
 tensor([-0.9069], dtype=torch.float64, grad_fn=<TanhBackward0>),
 tensor([-0.8935], dtype=torch.float64, grad_fn=<TanhBackward0>),
 tensor([0.8938], dtype=torch.float64, grad_fn=<TanhBackward0>)]

In [684]:
mlp.parameters()

[tensor([0.6883], dtype=torch.float64, requires_grad=True),
 tensor([0.5156], dtype=torch.float64, requires_grad=True),
 tensor([1.1972], dtype=torch.float64, requires_grad=True),
 tensor([-0.9718], dtype=torch.float64, requires_grad=True),
 tensor([-0.0549], dtype=torch.float64, requires_grad=True),
 tensor([0.0452], dtype=torch.float64, requires_grad=True),
 tensor([0.0214], dtype=torch.float64, requires_grad=True),
 tensor([-0.1884], dtype=torch.float64, requires_grad=True),
 tensor([0.8432], dtype=torch.float64, requires_grad=True),
 tensor([0.1579], dtype=torch.float64, requires_grad=True),
 tensor([-0.2189], dtype=torch.float64, requires_grad=True),
 tensor([0.8866], dtype=torch.float64, requires_grad=True),
 tensor([0.0846], dtype=torch.float64, requires_grad=True),
 tensor([-0.9130], dtype=torch.float64, requires_grad=True),
 tensor([0.6274], dtype=torch.float64, requires_grad=True),
 tensor([1.0763], dtype=torch.float64, requires_grad=True),
 tensor([0.0731], dtype=torch.float